## File: R/main.R

#' Run principal-components based multi-peak QTL test
#'
#' This function performs single- and multi-peak chromatin QTL mapping using the CACTI framework.
#'
#' @param chr Character. Chromosome identifier (e.g., "chr1").
#' @param file_qtl_cis_norm Character. Path to sum stats file with columns: phe_id, phe_chr, var_id, nom_pval, slope.
#' @param file_peak_group Character or NULL. Path to peak group file with columns: phe_id, phe_group. If NULL, groups are generated by `make_peak_group()`.
#' @param file_pheno_cov_residual Character or NULL. Path to phenotype residuals file, used to calculate pheno correlation as one of inputs of CACTI. If NULL, generated by `make_pheno_cov_residual()`.
#' @param n_pid Integer. Minimum number of peaks in a group for the multivariate test (default = 2).
#'
#' @return A list with:
#' * p_peak_group: data.frame of SNP-wise p-values per group (columns: group, snp, p).
#' * peak_group: the peak-group assignment used.
#' * pheno_cov_residual: phenotype residual matrix.
#' @importFrom data.table fread
#' @importFrom dplyr filter mutate group_by ungroup select relocate pull
#' @importFrom tidyr pivot_wider
#' @importFrom tibble enframe
#' @importFrom stats qchisq
#' @importFrom stringr str_glue
#' @importFrom ACAT ACAT
#' @export
cal_p <- function(
  chr,
  file_qtl_cis_norm,
  file_peak_group = NULL, file_pheno_meta = NULL, window_size = "50kb",
  file_pheno_cov_residual = NULL, file_pheno = NULL, file_cov = NULL,
  n_pid = 2
) {
  # Read sum stats
  qtl_cis_norm <- data.table::fread(file_qtl_cis_norm)
  
  # Read peak groups
  peak_group <- if (is.null(file_peak_group)) {
    if (is.null(file_pheno_meta)) {
      stop("Must provide 'file_pheno_meta' when 'file_peak_group' is NULL.")
    }
    
    make_peak_group(file_pheno_meta, window_size)
  } else {
    data.table::fread(file_peak_group)
  }
  
  # Read pheno
  pheno_cov_residual <- if (is.null(file_pheno_cov_residual)) {
    if (is.null(file_pheno) || is.null(file_cov)) {
      stop("Must provide 'file_pheno' and 'file_cov' when 'file_pheno_cov_residual' is NULL.")
    }
    
    make_pheno_cov_residual(file_pheno, file_cov)
  } else {
    data.table::fread(file_pheno_cov_residual)
  }
  
  # Compute Z-statistics
  qtl_cis_norm <- qtl_cis_norm %>%
    filter(phe_chr == !!chr) %>%
    mutate(z = sqrt(qchisq(nom_pval, df = 1, lower.tail = FALSE)) * sign(slope))
  
  # Annotate group sizes
  peak_group <- peak_group %>%
    filter(phe_id %in% unique(qtl_cis_norm$phe_id)) %>%
    group_by(phe_group) %>%
    mutate(size_phe_group = n()) %>%
    ungroup() %>%
    mutate(phe_group = str_glue("G_{phe_group}_n{size_phe_group}"))
  
  groups <- unique(peak_group$phe_group)
  result_list <- vector("list", length(groups))
  names(result_list) <- groups
  
  for (g in groups) {
    ids <- peak_group %>% filter(phe_group == !!g) %>% pull(phe_id)
    
    # Single-peak fallback
    if (length(ids) < n_pid) {
      result_list[[g]] <- qtl_cis_norm %>%
        filter(phe_id %in% ids) %>%
        select(var_id, nom_pval) %>%
        rename(snp = var_id, p = nom_pval) %>%
        mutate(group = !!g)
      next
    }
    
    # Build Z matrix
    z_mat <- qtl_cis_norm %>%
      filter(phe_id %in% ids) %>%
      select(phe_id, var_id, z) %>%
      pivot_wider(names_from = phe_id, values_from = z) %>%
      filter(complete.cases(.)) %>%
      column_to_rownames("var_id") %>%
      as.matrix()
    if (nrow(z_mat) == 0 || ncol(z_mat) < n_pid) next
    
    # Correlation matrix among peaks
    Sigma <- cor(pheno_cov_residual[, colnames(z_mat)])
    
    # Multivariate test via ACAT
    result_list[[g]] <- ModifiedPCOMerged_acat(Z.mat = z_mat, Sigma = Sigma) %>%
      tibble::enframe(name = "snp", value = "p") %>%
      mutate(group = !!g)
  }
  
  # Combine results
  p_peak_group <- bind_rows(result_list) %>% relocate(group)
  
  return(list(
    p_peak_group = p_peak_group,
    peak_group = peak_group,
    pheno_cov_residual = pheno_cov_residual
  ))
}

